name: Docker Test
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Simple bash script
        uses: ./.github/helm
        env:
          KUBECONFIGBASE64: "4422"
