name: Docker Test
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - ".github/**"
jobs:
  docker:
    runs-on: ubuntu-latest
    working-directory: test
    steps:
      - uses: actions/checkout@v2
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: 'yq -i ''.replicaCount = 2'' values.yaml; yq -i ''.image.repository = "nonsense"'' values.yaml'
      - name: Update git
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Author Name
          author_email: mail@example.com
          message: "Your commit message"
      # - name: Simple bash script
      # uses: ./.github/helm
      # env:
      #   KUBECONFIGBASE64: ${{ secrets.KUBECONFIGBASE64 }}
