name: Docker Test
on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -i '.replicaCount = 2' test/values.yaml
            yq -i '.image.repository = nonsense' test/values.yaml
      - name: Simple bash script
        uses: ./.github/helm
        env:
          KUBECONFIGBASE64: ${{ secrets.KUBECONFIGBASE64 }}
